CREATE TYPE "NutritionBasis" AS ENUM ('PER_100G', 'PER_100ML');

ALTER TABLE "Ingredient"
ADD COLUMN "energyKcal" DOUBLE PRECISION,
ADD COLUMN "energyKj" DOUBLE PRECISION,
ADD COLUMN "fat" DOUBLE PRECISION,
ADD COLUMN "saturates" DOUBLE PRECISION,
ADD COLUMN "carbohydrates" DOUBLE PRECISION,
ADD COLUMN "sugars" DOUBLE PRECISION,
ADD COLUMN "protein" DOUBLE PRECISION,
ADD COLUMN "salt" DOUBLE PRECISION,
ADD COLUMN "nutritionBasis" "NutritionBasis" NOT NULL DEFAULT 'PER_100G';
